import type { DetectedStack } from './types';

type Headers = Record<string, string>;

function headerIncludes(headers: Headers, key: string, substring: string): boolean {
  const val = headers[key.toLowerCase()];
  return val !== undefined && val.toLowerCase().includes(substring.toLowerCase());
}

function cookieIncludes(headers: Headers, substring: string): boolean {
  const cookie = headers['set-cookie'] ?? '';
  return cookie.toLowerCase().includes(substring.toLowerCase());
}

function bodyIncludes(body: string, substring: string): boolean {
  return body.toLowerCase().includes(substring.toLowerCase());
}

export function detectWaf(headers: Headers, body: string): string | null {
  if (
    'cf-ray' in headers ||
    (bodyIncludes(body, 'just a moment') && bodyIncludes(body, 'cloudflare')) ||
    bodyIncludes(body, '/cdn-cgi/')
  ) {
    return 'Cloudflare';
  }

  if (
    cookieIncludes(headers, 'wfvt_') ||
    bodyIncludes(body, 'wordfence') ||
    bodyIncludes(body, 'generated by wordfence')
  ) {
    return 'Wordfence';
  }

  if (
    'x-sucuri-id' in headers ||
    'x-sucuri-cache' in headers ||
    bodyIncludes(body, 'sucuri website firewall')
  ) {
    return 'Sucuri';
  }

  if (
    headerIncludes(headers, 'via', 'akamai') ||
    cookieIncludes(headers, 'ak_bmsc') ||
    (bodyIncludes(body, 'reference #') && bodyIncludes(body, 'akamai'))
  ) {
    return 'Akamai';
  }

  if (
    'x-iinfo' in headers ||
    cookieIncludes(headers, 'incap_ses') ||
    cookieIncludes(headers, '_incapsula_')
  ) {
    return 'Imperva';
  }

  if (cookieIncludes(headers, 'itsec-hb') || bodyIncludes(body, 'itsec')) {
    return 'Solid Security';
  }

  return null;
}

export function detectWebServer(headers: Headers): string | null {
  const server = headers['server']?.toLowerCase() ?? '';
  if (!server) return null;
  if (server.includes('apache')) return 'Apache';
  if (server.includes('nginx')) return 'Nginx';
  if (server.includes('litespeed')) return 'LiteSpeed';
  if (server.includes('caddy')) return 'Caddy';
  if (server.includes('iis') || server.includes('microsoft-iis')) return 'IIS';
  // Return the raw value when the server advertises itself but doesn't match known names
  return headers['server'] ?? null;
}

export function detectCdn(headers: Headers): string | null {
  if ('cf-ray' in headers) return 'Cloudflare';
  if (Object.keys(headers).some((k) => k.startsWith('fastly-'))) return 'Fastly';
  if (
    headerIncludes(headers, 'via', 'akamai') ||
    cookieIncludes(headers, 'ak_bmsc')
  ) {
    return 'Akamai';
  }
  if ('x-vercel-id' in headers) return 'Vercel';
  if ('x-nf-request-id' in headers) return 'Netlify';
  return null;
}

export function detectCms(headers: Headers, body: string): { cms: string | null; cms_theme: string | null } {
  const generator = (() => {
    const match = body.match(/<meta[^>]+name=["']generator["'][^>]+content=["']([^"']+)["']/i);
    return match?.[1]?.toLowerCase() ?? '';
  })();

  if (
    bodyIncludes(body, '/wp-content/') ||
    bodyIncludes(body, '/wp-includes/') ||
    generator.includes('wordpress') ||
    // Some WP sites remove the generator tag; check x-powered-by as a fallback
    headerIncludes(headers, 'x-powered-by', 'wordpress')
  ) {
    // TODO: Extract active theme name from body (/wp-content/themes/<name>/) for cms_theme
    const themeMatch = body.match(/\/wp-content\/themes\/([^/'"]+)/i);
    return { cms: 'WordPress', cms_theme: themeMatch?.[1] ?? null };
  }

  if (generator.includes('shopify') || bodyIncludes(body, 'myshopify.com')) {
    return { cms: 'Shopify', cms_theme: null };
  }

  if (generator.includes('webflow')) {
    return { cms: 'Webflow', cms_theme: null };
  }

  if (generator.includes('ghost')) {
    return { cms: 'Ghost', cms_theme: null };
  }

  return { cms: null, cms_theme: null };
}

export function buildDetectedStack(
  headers: Headers,
  body: string,
): DetectedStack {
  const waf = detectWaf(headers, body);
  const cdn = detectCdn(headers);
  // Only report CDN separately when it differs from the WAF vendor
  const cdnValue = cdn === waf ? null : cdn;
  const { cms, cms_theme } = detectCms(headers, body);

  return {
    web_server: detectWebServer(headers),
    cdn: cdnValue,
    waf,
    cms,
    cms_theme,
  };
}
