// Tranche D / Amendment D2 — RICH TRANSIENT ANALYSIS -> MINIMAL DURABLE EVIDENCE.
//
// Engines keep producing their existing rich results. Only the projections below
// may enter page_observations. Each projector is engine-specific and preserves the
// engine's actual conclusions; none is a generic stringify-and-truncate.
import type { PageEngineName } from './types';
import {
  EVIDENCE_PROJECTION_VERSION,
  MAX_DURABLE_OBSERVATION_BYTES,
  MAX_EVIDENCE_LIST_ITEMS,
  MAX_EVIDENCE_STRING_CHARS,
  MAX_EVIDENCE_TOKEN_CHARS,
  MAX_EVIDENCE_URL_CHARS,
  MAX_SCHEMA_PROPERTY_NAMES,
  MAX_SCHEMA_TYPES,
  MAX_SCHEMA_WALK_NODES,
} from './versions';

export class DurableEvidenceTooLargeError extends Error {
  constructor(readonly bytes: number) {
    super('durable_evidence_too_large');
  }
}

export class NoRegisteredProjectorError extends Error {
  constructor(readonly engine: string) {
    super('no_registered_projector');
  }
}

// ── bounded primitives ───────────────────────────────────────

interface Bounds {
  truncated: string[];
}

function boundedText(value: unknown, field: string, bounds: Bounds, max = MAX_EVIDENCE_STRING_CHARS): string | null {
  if (typeof value !== 'string' || value.length === 0) return null;
  if (value.length <= max) return value;
  bounds.truncated.push(field);
  return value.slice(0, max);
}

function boundedList(value: unknown, field: string, bounds: Bounds, maxItems = MAX_EVIDENCE_LIST_ITEMS, maxChars = MAX_EVIDENCE_STRING_CHARS): string[] {
  if (!Array.isArray(value)) return [];
  const out: string[] = [];
  for (const item of value) {
    if (out.length >= maxItems) {
      bounds.truncated.push(field);
      break;
    }
    if (typeof item !== 'string') continue;
    out.push(item.length > maxChars ? (bounds.truncated.push(`${field}[]`), item.slice(0, maxChars)) : item);
  }
  return out;
}

function count(value: unknown): number {
  return Array.isArray(value) ? value.length : 0;
}

function num(value: unknown): number {
  return typeof value === 'number' && Number.isFinite(value) ? value : 0;
}

function numOrNull(value: unknown): number | null {
  return typeof value === 'number' && Number.isFinite(value) ? value : null;
}

function bool(value: unknown): boolean {
  return value === true;
}

function obj(value: unknown): Record<string, unknown> {
  return value && typeof value === 'object' ? (value as Record<string, unknown>) : {};
}

function enumOf<T extends string>(value: unknown, allowed: readonly T[], fallback: T): T {
  return typeof value === 'string' && (allowed as readonly string[]).includes(value) ? (value as T) : fallback;
}

// ── 1. extraction_resilience ─────────────────────────────────
// Retains the band, the rule that produced it, every measure's numerator and
// denominator, per-check ids and statuses, and bounded structural counts.
// Drops extractA entirely (page text, headings, bindings, tables, footnotes,
// semantic sections), extractB.sample, every check detail/evidence string, the
// `lost` example arrays, and contradiction left/right/detail — all page prose.

function projectMeasure(value: unknown) {
  const m = obj(value);
  return {
    preserved: num(m.preserved),
    assessed: num(m.assessed),
    undeterminable: num(m.undeterminable),
    notApplicable: bool(m.notApplicable),
    ratio: numOrNull(m.ratio),
    lostCount: count(m.lost),
  };
}

function projectExtractionResilience(raw: unknown, bounds: Bounds) {
  const r = obj(raw);
  const measures = obj(r.measures);
  const delta = obj(measures.delta);
  const extractA = obj(r.extractA);
  const identity = obj(extractA.identity);
  const schema = obj(extractA.schema);
  const assets = obj(extractA.assets);
  const images = obj(assets.images);
  const extractB = obj(r.extractB);
  const meta = obj(r.meta);
  const visual = r.visualParity === null || r.visualParity === undefined ? null : obj(r.visualParity);

  return {
    band: boundedText(r.band, 'band', bounds),
    bandRule: boundedText(r.bandRule, 'bandRule', bounds),
    // Generated by the engine from counts, not copied from the page, but bounded anyway.
    bandReason: boundedText(r.bandReason, 'bandReason', bounds, 400),
    measures: {
      structural_resilience: projectMeasure(measures.structural_resilience),
      factual_resilience: projectMeasure(measures.factual_resilience),
      qualifier_resilience: projectMeasure(measures.qualifier_resilience),
      contradiction_count: num(measures.contradiction_count),
      // Kind + importance only. detail/left/right are page values.
      contradictions: (Array.isArray(measures.contradictions) ? measures.contradictions : [])
        .slice(0, MAX_EVIDENCE_LIST_ITEMS)
        .map(c => ({ kind: boundedText(obj(c).kind, 'contradictions[].kind', bounds, 64), important: bool(obj(c).important) })),
      delta: {
        aTextLength: num(delta.aTextLength),
        bTextLength: num(delta.bTextLength),
        bindingLossRatio: numOrNull(delta.bindingLossRatio),
        structuralRelationsLost: num(delta.structuralRelationsLost),
        structuralRelationsTotal: num(delta.structuralRelationsTotal),
      },
    },
    // id + status is the whole conclusion. label is a constant, detail and
    // evidence are prose drawn from the page.
    checks: (Array.isArray(r.checks) ? r.checks : []).slice(0, 40).map(c => ({
      id: boundedText(obj(c).id, 'checks[].id', bounds, 64),
      status: boundedText(obj(c).status, 'checks[].status', bounds, 32),
      evidenceCount: count(obj(c).evidence),
    })),
    structure: {
      outlineCount: count(extractA.outline),
      bindingCount: count(extractA.bindings),
      relationCount: count(extractA.relations),
      tableCount: count(extractA.tables),
      figureCount: count(extractA.figures),
      footnoteCount: count(extractA.footnotes),
      semanticSectionCount: count(extractA.semanticSections),
      schemaTypeCount: count(schema.types),
      schemaBlockCount: num(schema.blockCount),
      schemaHasMalformed: bool(schema.hasMalformed),
      schemaDeclaredValueCount: count(schema.declaredValues),
      schemaOrganizationNameCount: count(schema.organizationNames),
      images: {
        total: num(images.total),
        withAlt: num(images.withAlt),
        withoutAlt: num(images.withoutAlt),
        decorative: num(images.decorative),
      },
      imageCandidateCount: count(assets.imageCandidates),
      tables: num(assets.tables),
      svg: num(assets.svg),
      canvas: num(assets.canvas),
      iframes: num(assets.iframes),
      jsonLdBlocks: num(assets.jsonLdBlocks),
    },
    // Presence, not content. The engine's conclusions turn on whether these
    // signals exist and where they came from, not on their prose.
    identity: {
      hasCanonicalUrl: typeof identity.canonicalUrl === 'string' && identity.canonicalUrl.length > 0,
      hasTitle: typeof identity.title === 'string' && identity.title.length > 0,
      hasMetaDescription: typeof identity.metaDescription === 'string' && identity.metaDescription.length > 0,
      hasPrimaryH1: typeof identity.primaryH1 === 'string' && identity.primaryH1.length > 0,
      hasOgSiteName: typeof identity.ogSiteName === 'string' && identity.ogSiteName.length > 0,
      hasSchemaOrgName: typeof identity.schemaOrgName === 'string' && identity.schemaOrgName.length > 0,
      entitySource: enumOf(identity.entitySource, ['json_ld', 'og_site_name', 'title_suffix', 'none'] as const, 'none'),
      topicSource: enumOf(identity.topicSource, ['h1', 'og_title', 'title', 'none'] as const, 'none'),
    },
    // Lengths only. extractB.sample is page prose.
    extractB: { length: num(extractB.length), tokenCount: num(extractB.tokenCount) },
    visualParity: visual === null ? null : {
      status: boundedText(visual.status, 'visualParity.status', bounds, 32),
      claimCount: count(visual.claims),
      comparisonCount: count(visual.comparisons),
    },
    meta: {
      increment: num(meta.increment),
      engine_version: boundedText(meta.engine_version, 'meta.engine_version', bounds, 64),
      extract_a: boundedText(meta.extract_a, 'meta.extract_a', bounds, 64),
      extract_b: boundedText(meta.extract_b, 'meta.extract_b', bounds, 64),
      vision_assessed: bool(meta.vision_assessed),
      scoring: boundedText(meta.scoring, 'meta.scoring', bounds, 64),
    },
  };
}

// ── 2. structured_data ───────────────────────────────────────
// Drops blocksText (raw JSON-LD source) and nodes (parsed CMS objects) entirely.
// Those are the carriers for articleBody, transcript, reviews and FAQ answers.
// Retains the structural findings: presence, malformedness, block count, the
// declared @type vocabulary and the top-level property-name vocabulary.

function collectPropertyNames(nodes: unknown[], bounds: Bounds): { names: string[]; total: number; truncated: boolean } {
  const names = new Set<string>();
  let total = 0;
  let visited = 0;
  const queue: unknown[] = [...nodes];
  while (queue.length > 0) {
    if (visited >= MAX_SCHEMA_WALK_NODES) return { names: [...names], total, truncated: true };
    const node = queue.shift();
    visited += 1;
    if (Array.isArray(node)) {
      for (const child of node) queue.push(child);
      continue;
    }
    if (!node || typeof node !== 'object') continue;
    for (const [key, value] of Object.entries(node as Record<string, unknown>)) {
      total += 1;
      if (names.size < MAX_SCHEMA_PROPERTY_NAMES) {
        names.add(key.length > 100 ? (bounds.truncated.push('propertyNames[]'), key.slice(0, 100)) : key);
      }
      if (key === '@graph' || Array.isArray(value)) queue.push(value);
    }
  }
  return { names: [...names], total, truncated: names.size >= MAX_SCHEMA_PROPERTY_NAMES };
}

function projectStructuredData(raw: unknown, bounds: Bounds) {
  const r = obj(raw);
  const allTypes = Array.isArray(r.types) ? r.types.filter(t => typeof t === 'string') : [];
  const nodes = Array.isArray(r.nodes) ? r.nodes : [];
  const props = collectPropertyNames(nodes, bounds);
  return {
    hasSchema: bool(r.hasSchema),
    hasMalformed: bool(r.hasMalformed),
    blockCount: num(r.blockCount),
    nodeCount: nodes.length,
    typeCount: allTypes.length,
    types: boundedList(allTypes.slice(0, MAX_SCHEMA_TYPES), 'types', bounds, MAX_SCHEMA_TYPES, 100),
    typesTruncated: allTypes.length > MAX_SCHEMA_TYPES,
    propertyNameCount: props.total,
    propertyNames: props.names.sort(),
    propertyNamesTruncated: props.truncated,
  };
}

// ── 3. content_delivery ──────────────────────────────────────
// Already numeric, boolean and fixed-vocabulary. Retained whole so its analysis
// semantics are unchanged; the indicator list is bounded defensively.

function projectContentDelivery(raw: unknown, bounds: Bounds) {
  const r = obj(raw);
  return {
    html_bytes: num(r.html_bytes),
    text_bytes: num(r.text_bytes),
    text_html_ratio: num(r.text_html_ratio),
    js_challenge_detected: bool(r.js_challenge_detected),
    challenge_indicators: boundedList(r.challenge_indicators, 'challenge_indicators', bounds, MAX_EVIDENCE_LIST_ITEMS, 100),
    content_appears_rendered: bool(r.content_appears_rendered),
    status: boundedText(r.status, 'status', bounds, 32),
  };
}

// ── 4. meta_tags ─────────────────────────────────────────────
// Short metadata values are themselves the evidence. Retained, explicitly bounded,
// so an arbitrarily long meta content attribute cannot create durable storage.

function projectMetaTags(raw: unknown, bounds: Bounds) {
  const r = obj(raw);
  // A robots directive's meaning is its token set. Retaining the raw attribute
  // would let an arbitrarily long content="" carry page prose into storage up to
  // the string bound, so the directive is tokenized instead: lossless for real
  // directives, and it reduces a prose blob to a single bounded token.
  const rawCanonical = typeof r.canonical === 'string' && r.canonical.length > 0 ? r.canonical : null;
  const canonicalUrl = rawCanonical === null || /\s/.test(rawCanonical)
    ? null
    : boundedText(rawCanonical, 'canonical', bounds, MAX_EVIDENCE_URL_CHARS);
  const rawDirective = typeof r.robots_directive === 'string' ? r.robots_directive : null;
  const tokens = rawDirective === null ? [] : rawDirective
    .split(',')
    .map(t => t.trim())
    .filter(Boolean)
    .slice(0, MAX_EVIDENCE_LIST_ITEMS)
    .map(t => (t.length > MAX_EVIDENCE_TOKEN_CHARS ? (bounds.truncated.push('robots_directives[]'), t.slice(0, MAX_EVIDENCE_TOKEN_CHARS)) : t));
  if (rawDirective !== null && rawDirective.split(',').filter(t => t.trim()).length > MAX_EVIDENCE_LIST_ITEMS) {
    bounds.truncated.push('robots_directives');
  }
  return {
    hasRobotsDirective: rawDirective !== null && rawDirective.length > 0,
    robots_directives: tokens,
    robots_directive_chars: rawDirective === null ? 0 : rawDirective.length,
    ai_blocking_directives: boundedList(r.ai_blocking_directives, 'ai_blocking_directives', bounds, MAX_EVIDENCE_LIST_ITEMS, MAX_EVIDENCE_TOKEN_CHARS),
    // A canonical href containing whitespace is not URL-shaped. Retaining it
    // would open a prose channel, so it is rejected rather than bounded.
    canonical: canonicalUrl,
    canonical_rejected: rawCanonical !== null && canonicalUrl === null ? 'not_url_shaped' : null,
    status: boundedText(r.status, 'status', bounds, 32),
  };
}

// ── registry ─────────────────────────────────────────────────

const PROJECTORS: Record<PageEngineName, (raw: unknown, bounds: Bounds) => unknown> = {
  extraction_resilience: projectExtractionResilience,
  structured_data: projectStructuredData,
  content_delivery: projectContentDelivery,
  meta_tags: projectMetaTags,
};

export const REGISTERED_PROJECTOR_NAMES: readonly string[] = Object.freeze(Object.keys(PROJECTORS));

export function hasProjector(engine: string): boolean {
  return Object.prototype.hasOwnProperty.call(PROJECTORS, engine);
}

/**
 * The only path by which an engine result may become durable evidence.
 * Throws for an unregistered engine, and for a projection that exceeds the
 * durable ceiling — the caller records an explicit failure rather than
 * persisting a truncated or oversized payload.
 */
export function projectDurableEvidence(engine: string, raw: unknown): unknown {
  const projector = PROJECTORS[engine as PageEngineName];
  if (!projector) throw new NoRegisteredProjectorError(engine);
  const bounds: Bounds = { truncated: [] };
  const projected = projector(raw, bounds);
  const durable = {
    ...(projected as Record<string, unknown>),
    evidence_projection_version: EVIDENCE_PROJECTION_VERSION,
    bounds_applied: [...new Set(bounds.truncated)].sort(),
  };
  const bytes = Buffer.byteLength(JSON.stringify(durable));
  if (bytes > MAX_DURABLE_OBSERVATION_BYTES) throw new DurableEvidenceTooLargeError(bytes);
  return durable;
}
